#!/bin/sh
#
# !!! Managed by Puppet !!!

daemon="/usr/sbin/unbound"
daemon_flags="-c /var/unbound/etc/unbound.conf"

. /etc/rc.d/rc.subr

pexp="unbound${daemon_flags:+ ${daemon_flags}}"

rc_start() {
	/usr/sbin/unbound-checkconf > /dev/null && \
	    ${rcexec} "unbound ${daemon_flags}"
}

rc_cmd $1
